Blog/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from Blog import views
from Blog.views import BlogViewSet

from Pet_Shop import settings

router = DefaultRouter()
router.register('posts', BlogViewSet, basename='spa_posts')

urlpatterns = [
    path('blog/', views.BlogView.as_view(), name='blog_main'),
    path('blog/add_post/', views.AddPost.as_view(), name='add_post'),
    path('blog/add_tag/', views.AddTag.as_view(), name='add_tag'),
    path('blog/delete_post/<slug:slug>/', views.DeletePostView.as_view(), name='delete_post'),
    path('blog/editorial/', views.AuthorPage.as_view(), name='editorial'),
    path('blog/editorial/<slug:slug>/', views.AuthorPostView.as_view(), name='view_post'),
    path('blog/edit_post/<slug:slug>/', views.EditPost.as_view(), name='edit_post'),
    path('blog/tag/<slug:tag_slug>/', views.TagView.as_view(), name='tag'),
    path('blog/author/<slug:author>', views.AuthorView.as_view(), name='post_authors'),
    path('blog/<slug:slug>/', views.PostView.as_view(), name='read_post'),
    path('spa/blog/', include(router.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pet_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page

from Pet_Shop.views import page_not_found, server_error, permission_error, request_error, change_theme_view
from django.contrib.sitemaps.views import sitemap
from Pet_Shop.sitemaps import sitemaps


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path('cookies', include("cookie_consent.urls")),
    path('', include('Home_Page.urls')),
    path('', include('Shop.urls')),
    path('', include('Blog.urls')),
    path('', include('User.urls', namespace='User')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('google_accounts/', include('allauth.urls'), name='google_auth'),
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('change_theme/', change_theme_view, name='change_theme'),
    path('search/', include('Search.urls')),

]

handler404 = page_not_found
handler500 = server_error
handler403 = permission_error
handler400 = request_error

admin.site.site_header = 'Pet_Shop Administration'
admin.site.index_header = 'Pet_Shop Administration'

Search/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from Blog.models import Post
from Pet_Shop import settings
from Search import views
from Shop.models import Product

app_name = 'search'

urlpatterns = [
    path('', views.SearchView.as_view(), name='search_main'),
    path('search_results/posts/<str:search>',
         views.PostSearchResults.as_view(queryset=Post.objects.all()),
         name='posts_search_results'),
    path('search_results/products/<str:search>',
         views.ProductSearchResults.as_view(queryset=Product.objects.all()),
         name='products_search_results'),

]

Search/models.py
from django.db import models

# Create your models here.

Search/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView

from Blog.models import Post
from Search.services import model_filter, queryset_filter
from Shop.models import Product


class SearchView(View):
    template_name = 'Search/Search.html'

    def get(self, request, *args, **kwargs):
        query = request.GET.get('search', None)
        post_search_results = model_filter(Post, query)
        product_search_results = model_filter(Product, query)
        return render(
            request=request,
            template_name=self.template_name,
            context={
                'search': query or '',
                'post_search_results': post_search_results[:3],
                'post_search_results_count': post_search_results.count(),
                'product_search_results': product_search_results[:5],
                'product_search_results_count': product_search_results.count(),
            }
        )


class FullSearchResults(ListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'search': self.request.path.split('/')[-1],
            # 'last': self.get_pagination_url()
        })
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.path.split('/')[-1]
        return queryset_filter(queryset, query)


class PostSearchResults(FullSearchResults):
    template_name = 'Search/Search_results_posts.html'
    paginate_by = 4


class ProductSearchResults(FullSearchResults):
    template_name = 'Search/Search_results_products.html'
    paginate_by = 10

Search/templates/Search/Search.html
{% extends 'base.html' %}

{% block title %}
    Search results for '{{ search }}'
{% endblock %}

{% block content %}
    <div class="main_container container-fluid min-vh-100 d-flex flex-column pt-5 mt-5">
        <div class="row main_block mb-5 flex-grow-1 mt-5">
            <h2 class="form__title">You asked for "{{ search }}"</h2>
                {% if product_search_results or post_search_results %}
                        {% if product_search_results %}
                            <h3 class="mt-4">Here are some products matching your question!</h3>
                            {% for p in product_search_results %}
                                {% include 'Shop/Product_card.html' %}
                            {% endfor %}
                            {% if product_search_results_count > 5 %}
                                <a href="{% url 'search:products_search_results' search %}" class="mt-2 fs-4">
                                    Show all {{ product_search_results_count }} products
                                </a>
                            {% endif %}
                        {% else %}
                        <h3 class="mt-4">There are no products matching your question.</h3>
                        {% endif %}

                        {% if post_search_results %}
                            <h3 class="mt-5">Here are some posts matching your question!</h3>
                            {% for p in post_search_results %}
                                {% include 'Blog/Post_medium.html' %}
                            {% endfor %}
                            {% if post_search_results_count > 3 %}
                                <a href="{% url 'search:posts_search_results' search %}" class="mt-2 fs-4">
                                    Show all {{ post_search_results_count }} posts
                                </a>
                            {% endif %}
                        {% else %}
                        <h3 class="mt-5">There are no posts matching your question.</h3>
                        {% endif %}
                {% else %}
                    <h3 class="mt-5">There are no products or posts matching your question.</h3>
                {% endif %}
        </div>
    </div>
{% endblock %}

Search/templates/Search/Search_results_posts.html
{% extends 'base.html' %}

{% block title %}
    Search results
{% endblock %}

{% block content %}
    <div class="main_container container-fluid h-100 d-flex flex-column pt-5 mt-5">
        <div class="row main_block mb-5 flex-grow-1 mt-5">
            <h2 class="form__title">Here are all our posts which refer to "{{ search }}"</h2>
            {% for p in object_list %}
                {% include 'Blog/Post_medium.html' %}
            {% endfor %}
        </div>
    </div>

    {% include 'pagination.html' %}

{% endblock %}

Search/templates/Search/Search_results_products.html
{% extends 'base.html' %}

{% block title %}
    Search results
{% endblock %}

{% block content %}
    <div class="main_container container-fluid h-100 d-flex flex-column pt-5 mt-5">
        <div class="row main_block mb-5 flex-grow-1 mt-5">
            <h2 class="form__title">Here are all our products which refer to "{{ search }}"</h2>
            {% for p in object_list %}
                {% include 'Shop/Product_card.html' %}
            {% endfor %}
        </div>
    </div>

    {% include 'pagination.html' %}

{% endblock %}