Blog/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from Blog import views
from Blog.views import BlogViewSet

from Pet_Shop import settings

router = DefaultRouter()
router.register('posts', BlogViewSet, basename='spa_posts')

urlpatterns = [
    path('blog/', views.BlogView.as_view(), name='blog_main'),
    path('blog/add_post/', views.AddPost.as_view(), name='add_post'),
    path('blog/add_tag/', views.AddTag.as_view(), name='add_tag'),
    path('blog/delete_post/<slug:slug>/', views.DeletePostView.as_view(), name='delete_post'),
    path('blog/editorial/', views.AuthorPage.as_view(), name='editorial'),
    path('blog/editorial/<slug:slug>/', views.AuthorPostView.as_view(), name='view_post'),
    path('blog/edit_post/<slug:slug>/', views.EditPost.as_view(), name='edit_post'),
    path('blog/tag/<slug:tag_slug>/', views.TagView.as_view(), name='tag'),
    path('blog/author/<slug:author>', views.AuthorView.as_view(), name='post_authors'),
    path('blog/<slug:slug>/', views.PostView.as_view(), name='read_post'),
    path('spa/blog/', include(router.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pet_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page

from Pet_Shop.views import page_not_found, server_error, permission_error, request_error, change_theme_view
from django.contrib.sitemaps.views import sitemap
from Pet_Shop.sitemaps import sitemaps


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path('cookies', include("cookie_consent.urls")),
    path('', include('Home_Page.urls')),
    path('', include('Shop.urls')),
    path('', include('Blog.urls')),
    path('', include('User.urls', namespace='User')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('google_accounts/', include('allauth.urls'), name='google_auth'),
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('change_theme/', change_theme_view, name='change_theme'),
    path('search/', include('Search.urls')),

]

handler404 = page_not_found
handler500 = server_error
handler403 = permission_error
handler400 = request_error

admin.site.site_header = 'Pet_Shop Administration'
admin.site.index_header = 'Pet_Shop Administration'

User/urls.py
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from django.urls import path
from User import views

app_name = 'User'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/login/', views.UserLogin.as_view(), name='login'),
    path('accounts/profile/', views.ProfilePage.as_view(), name='profile'),
    path('register/', views.register_user, name='register'),
    path('password-change/', views.UserPasswordChangeView.as_view(), name='change_password'),
    path('password-change/done/', views.password_changed, name='password_changed'),
    path('password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

User/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify

from Pet_Shop import settings
from User.services import create_theme_entry_for_user


class User(AbstractUser):
    profile_photo = models.ImageField(upload_to='avatars/%Y/%m/%d', blank=True,
                                      default=settings.DEFAULT_USER_IMAGE,
                                      verbose_name='Avatar')
    user_slug = models.SlugField(unique=True)
    user_postalcode = models.PositiveIntegerField(blank=True, null=True)
    user_address = models.CharField(max_length=512, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.user_slug = slugify(self.username)
        super().save(*args, **kwargs)


class UserTheme(models.Model):
    user_theme_user = models.OneToOneField(to=User, on_delete=models.CASCADE, related_name='theme')
    user_theme_theme = models.IntegerField(default=0)

User/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm
from image_uploader_widget.widgets import ImageUploaderWidget

from User.services import check_email


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Username',
                               widget=forms.TextInput(attrs={'class': 'form-control back-drop text-center',
                                                             'placeholder': 'Username'}))
    # email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={'class': 'form-control back-drop'}))
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'form-control back-drop text-center',
                                                                 'placeholder': 'Password'}))


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Username',
                               widget=forms.TextInput(attrs={'class': 'form-control back-drop text-center',
                                                             'placeholder': 'Username'}))
    email = forms.EmailField(label='E-mail',
                             widget=forms.EmailInput(attrs={'class': 'form-control back-drop text-center',
                                                            'placeholder': 'E-mail'}))
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={'class': 'form-control back-drop text-center',
                                                                  'placeholder': 'Invent a strong password'}))
    password2 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={'class': 'form-control back-drop text-center',
                                                                  'placeholder': 'Repeat your password'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')
        # labels = {'first_name': 'What is your first name?', 'last_name': 'What is your last name?'}

    def clean_email(self):
        return check_email(self.cleaned_data['email'])


class ChangePassword(PasswordChangeForm):
    old_password = forms.CharField(label='Old password',
                                   widget=forms.PasswordInput(attrs={'class': 'form-control back-drop text-center',
                                                                     'placeholder': 'Old password'}))
    new_password1 = forms.CharField(label='New password',
                                    widget=forms.PasswordInput(attrs={'class': 'form-control back-drop text-center',
                                                                      'placeholder': 'Invent a strong password'}))
    new_password2 = forms.CharField(label='New password repeat',
                                    widget=forms.PasswordInput(attrs={'class': 'form-control back-drop text-center',
                                                                      'placeholder': 'Repeat your new password'}))


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control back-drop text-center',
                                                            'placeholder': 'Enter your e-mail'}))


class UserPasswordResetCompleteForm():
    pass


class ProfilePageForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'user_postalcode', 'user_address', 'profile_photo']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control back-drop text-center'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control back-drop text-center'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control back-drop text-center'},),
            'user_postalcode': forms.NumberInput(attrs={'class': 'form-control back-drop text-center'}),
            'user_address': forms.TextInput(attrs={'class': 'form-control back-drop text-center'},),
            'profile_photo': ImageUploaderWidget(attrs={'accept': 'image/png', 'class': 'w-75'})
        }
        labels = {
            'username': 'Username',
            'first_name': 'First name',
            'last_name': 'Last name',
        }

User/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView

from Pet_Shop import settings
from User.forms import UserLoginForm, UserRegisterForm, ChangePassword, UserPasswordResetForm, ProfilePageForm
from django.shortcuts import render, redirect

from User.services import save_new_user


class UserLogin(LoginView):
    form_class = UserLoginForm
    template_name = 'User/Login.html'
    extra_context = {'title': 'Log In'}
    redirect_authenticated_user = True


class ProfilePage(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfilePageForm
    template_name = 'User/Profile_page.html'
    extra_context = {
        'title': "Profile page"
    }

    def get_success_url(self):
        return reverse_lazy('User:profile')

    def get_object(self, queryset=None):
        return self.request.user


def register_user(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            save_new_user(form)
            return redirect('home:home')
    else:
        form = UserRegisterForm()
    return render(request, 'User/Register.html', {'form': form})


class UserPasswordChangeView(PasswordChangeView):
    form_class = ChangePassword
    success_url = reverse_lazy('User:password_changed')
    template_name = 'User/Password_change.html'
    extra_context = {'title': 'Password change'}


def password_changed(request):
    return render(request, 'User/Password_change_success.html')


class UserPasswordResetView(PasswordResetView):
    form_class = UserPasswordResetForm
    template_name = 'User/Password_reset_form.html'
    email_template_name = 'User/password_reset_email.html'
    extra_context = {'title': 'Password reset'}
    success_url = reverse_lazy('User:password_reset_done')


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'User/Password_reset_done.html'
    extra_context = {'title': 'Password reset'}


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'User/Password_reset_confirm.html'
    extra_context = {'title': 'Change password'}
    success_url = reverse_lazy('User:password_reset_complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'User/Password_change_success.html'
    extra_context = {'title': 'Done!'}

User/templates/User/Login.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}
{% load static %}
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{your-app-id}',
      cookie     : true,
      xfbml      : true,
      version    : '{api-version}'
    });

    FB.AppEvents.logPageView();

  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

{% block content %}
    <div class="main_container min-vh-100 hero-section d-flex align-items-center justify-content-center">
        <img src="{% static 'Images/Login_Cat.png' %}" alt="" class="login-catto">
        <div class="row auto mt-5 text-center">
            {% include 'User/Login_register.html' %}
        </div>
    </div>
{% endblock %}

User/templates/User/Login_register.html
{% load socialaccount %}
{% load static %}


<div class="col-12 mt-3 d-flex align-items-center justify-content-center">
    <h3 class="col-12 text-center" style="color: rgba(243, 148, 34, 1)">
        Already have an account?<br>Login!
    </h3>
</div>
<div class="col-12 mt-3 d-flex align-items-center justify-content-center">
    <form method="post" style="width: 35%" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for f in form %}
            <p>{{ f }}</p>
            <p>{{ f.errors }}</p>
        {% endfor %}
        <button type="submit" class="btn btn-primary" style="height: 2.5rem; width: 100%">
            Log in
        </button>
    </form>
</div>
<div class="col-12 mt-3 d-flex align-items-center justify-content-center">
    <a class="text-center " href="/password-reset">
        Forgot the password?
    </a>
</div>
<h3 <h3 class="text-center mt-3" style="color: rgba(243, 148, 34, 1)">Or login with your socials</h3>
<div class="col-12 mt-2 d-flex align-items-center justify-content-center">
    <a href="{% url 'social:begin' 'facebook' %}" title="Login with Facebook" class="ps-2 pe-2">
        <i class="fa-brands fa-facebook fa-2xl"></i>
    </a>
    <a href="{% provider_login_url 'google' %}" title="Login with Google"  class="ps-2 pe-2">
        <i class="fa-brands fa-google fa-2xl"></i>
    </a>
</div>
<div class="col-12 mt-3 d-flex align-items-center justify-content-center">
    <h3 class="text-center mt-3"
        style="color: rgba(243, 148, 34, 1)">
        First time with us?
    </h3>
</div>

<div class="col-12 mt-3 d-flex align-items-center justify-content-center">
    <a href="/register" role="button"
       class="btn btn-primary mt-1"
       style="height: 2.5rem; width: 35%">
        Create an account!
    </a>
</div>
</div>

User/templates/User/Password_change.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}
{% load static %}

{% block content %}
    <div class="main_container min-vh-100 hero-section d-flex align-items-center justify-content-center">
        <img src="{% static 'Images/Login_Cat.png' %}" alt="" class="login-catto">
        <div class="row auto mt-5 text-center">
            <div class="col-12 mt-3 d-flex align-items-center justify-content-center">
                <h3 class="col-12 text-center">
                    You can change your password here
                </h3>
            </div>
            <div class="col-12 mt-3 d-flex align-items-center justify-content-center">
                <form method="post" style="width: 35%" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for f in form %}
                        <p>{{ f }}</p>
                        <p>{{ f.errors }}</p>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary" style="height: 2.5rem; width: 100%">
                        Change password
                    </button>
                </form>
        </div>
    </div>
{% endblock %}

User/templates/User/Password_change_success.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}
{% load static %}

{% block content %}
    <div class="main_container min-vh-100 hero-section d-flex align-items-center justify-content-center">
        <div class="row main_block mt-5 text-center">
            <h3>Your password has been successfully changed!</h3>
        </div>
    </div>
{% endblock %}

User/templates/User/Password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}
{% load static %}

{% block content %}
    <div class="main_container min-vh-100 hero-section d-flex align-items-center justify-content-center">
        <img src="{% static 'Images/Login_Cat.png' %}" alt="" class="login-catto">


            <div class="col-12 mt-3 d-flex align-items-center justify-content-center text-center">

                <form method="post" style="width: 35%">
                <h3 style="margin-bottom: 2rem">Create a new password</h3>
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for f in form %}
                        <p>{{ f }}</p>
                        <p>{{ f.errors }}</p>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary" style="height: 2.5rem; width: 100%">
                        Change my password
                    </button>
                </form>
            </div>

    </div>
{% endblock %}

User/templates/User/Password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}
{% load static %}

{% block content %}
    <div class="main_container min-vh-100 hero-section d-flex align-items-center justify-content-center">
        <img src="{% static 'Images/Login_Cat.png' %}" alt="" class="login-catto">


            <div class="col-12 mt-3 d-flex align-items-center justify-content-center text-center">

                <form method="post" style="width: 35%">
                <h3 style="margin-bottom: 2rem">We've sent you an email
                    with the instructions for resetting your password</h3>
                </form>
            </div>

    </div>
{% endblock %}

User/templates/User/Password_reset_form.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}
{% load static %}

{% block content %}
    <div class="main_container min-vh-100 hero-section d-flex align-items-center justify-content-center">
        <img src="{% static 'Images/Login_Cat.png' %}" alt="" class="login-catto">


            <div class="col-12 mt-3 d-flex align-items-center justify-content-center text-center">

                <form method="post" style="width: 35%">
                <h3 style="margin-bottom: 2rem">Password reset</h3>
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for f in form %}
                        <p>{{ f }}</p>
                        <p>{{ f.errors }}</p>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary" style="height: 2.5rem; width: 100%">
                        Send me an instruction
                    </button>
                </form>
            </div>

    </div>
{% endblock %}

User/templates/User/Profile_page.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}



{% block content %}
    <div class="main_container min-vh-100 hero-section d-flex align-items-center justify-content-center">
        <div class="row container-fluid auto mt-5 text-center mb-5">
            <div class="col-lg-3 mt-3 align-items-center justify-content-center">
                <div class="row mt-2 text-center">
                    <h2>{{ user.username }}</h2>
                </div>
                <div class="row mt-2 justify-content-center">
                    <img src="{{ user.profile_photo.url }}" alt="" class="user_photo">
                </div>
                <div class="row mt-2 justify-content-center">
                    <a class="btn btn-primary" href="/password-change" style="height: 2.5rem; width: 75%">Change
                        password</a>
                </div>
                <div class="row mt-2 justify-content-center">
                    <a class="btn btn-primary" href="/logout" style="height: 2.5rem; width: 75%">Log out</a>
                </div>
            </div>
            <div class="col-lg-6 mt-3 align-items-center justify-content-center">
                <div class="row mt-2 text-center">
                    <h3 class="col-12 text-center">
                        You can change your profile info here
                    </h3>
                </div>
                <div class="row mt-2 text-center justify-content-center">
                    <form method="post" enctype="multipart/form-data" style="width: 65%">
                    {{ form.media }}
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% for f in form %}
                            <p class="form__title">{{ f.label }} </p>
                            <p>{{ f }}</p>
                            <p>{{ f.errors }}</p>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary mt-4" style="height: 2.5rem; width: 100%">
                            Submit
                        </button>
                    </form>
                </div>
            </div>
            <div class="col-lg-3 mt-3 align-items-center justify-content-center">

            </div>


        </div>
    </div>

{% endblock %}

User/templates/User/Register.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}
{% load static %}

{% block content %}
    <div class="main_container min-vh-100 hero-section d-flex align-items-center justify-content-center">
        <img src="{% static 'Images/Login_Cat.png' %}" alt="" class="login-catto">
        <div class="row auto mt-5 text-center">
            <div class="col-12 mt-3 d-flex align-items-center justify-content-center">
                <h3 class="col-12 text-center">
                    Welcome!<br>Fill out this form to create an account!
                </h3>
            </div>
            <div class="col-12 mt-3 d-flex align-items-center justify-content-center">
                <form method="post" style="width: 35%" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for f in form %}
                        <p>{{ f }}</p>
                        <p>{{ f.errors }}</p>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary" style="height: 2.5rem; width: 100%">
                        Create an account
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

User/templates/User/Successfull_reg.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}
{% load static %}

{% block content %}
    <div class="main_container min-vh-100 hero-section d-flex align-items-center justify-content-center">
        <div class="row main_block mt-5 text-center">
            <p>You have successfully registered!</p>
        </div>
    </div>
{% endblock %}

User/templates/User/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'User:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}