Blog/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from Blog import views
from Blog.views import BlogViewSet

from Pet_Shop import settings

router = DefaultRouter()
router.register('posts', BlogViewSet, basename='spa_posts')

urlpatterns = [
    path('blog/', views.BlogView.as_view(), name='blog_main'),
    path('blog/add_post/', views.AddPost.as_view(), name='add_post'),
    path('blog/add_tag/', views.AddTag.as_view(), name='add_tag'),
    path('blog/delete_post/<slug:slug>/', views.DeletePostView.as_view(), name='delete_post'),
    path('blog/editorial/', views.AuthorPage.as_view(), name='editorial'),
    path('blog/editorial/<slug:slug>/', views.AuthorPostView.as_view(), name='view_post'),
    path('blog/edit_post/<slug:slug>/', views.EditPost.as_view(), name='edit_post'),
    path('blog/tag/<slug:tag_slug>/', views.TagView.as_view(), name='tag'),
    path('blog/author/<slug:author>', views.AuthorView.as_view(), name='post_authors'),
    path('blog/<slug:slug>/', views.PostView.as_view(), name='read_post'),
    path('spa/blog/', include(router.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home_Page/urls.py
from django.urls import path

from .views import *

app_name = 'home'


urlpatterns = [
    path('', home_page, name='home'),

]

Pet_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page

from Pet_Shop.views import page_not_found, server_error, permission_error, request_error, change_theme_view
from django.contrib.sitemaps.views import sitemap
from Pet_Shop.sitemaps import sitemaps


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path('cookies', include("cookie_consent.urls")),
    path('', include('Home_Page.urls')),
    path('', include('Shop.urls')),
    path('', include('Blog.urls')),
    path('', include('User.urls', namespace='User')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('google_accounts/', include('allauth.urls'), name='google_auth'),
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('change_theme/', change_theme_view, name='change_theme'),
    path('search/', include('Search.urls')),

]

handler404 = page_not_found
handler500 = server_error
handler403 = permission_error
handler400 = request_error

admin.site.site_header = 'Pet_Shop Administration'
admin.site.index_header = 'Pet_Shop Administration'

Search/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from Blog.models import Post
from Pet_Shop import settings
from Search import views
from Shop.models import Product

app_name = 'search'

urlpatterns = [
    path('', views.SearchView.as_view(), name='search_main'),
    path('search_results/posts/<str:search>',
         views.PostSearchResults.as_view(queryset=Post.objects.all()),
         name='posts_search_results'),
    path('search_results/products/<str:search>',
         views.ProductSearchResults.as_view(queryset=Product.objects.all()),
         name='products_search_results'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Pet Shop
        {% endblock %}
    </title>

    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'Images/favicon.png' %}"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href={% static 'css/bootstrap_skin.css' %} rel="stylesheet" media="screen">

    {% if user.is_authenticated and user.theme.user_theme_theme == 1 %}
        <link href={% static 'css/skin_bright.css' %} rel="stylesheet" media="screen">
    {% else %}
        <link href={% static 'css/skin_default.css' %} rel="stylesheet" media="screen">
    {% endif %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous" defer></script>
    <script src="{% static 'js/bootstrap5.modal.forms.min.js' %}" defer></script>
    <script src="{% static 'js/split_type.min.js' %}" defer></script>
    <script src="{% static 'js/gsap.min.js' %}" defer></script>
    <script src="{% static 'js/ScrollTrigger.min.js' %}" defer></script>
    <script src="{% static 'js/ScrollSmoother.min.js' %}" defer></script>
    <script src="https://kit.fontawesome.com/9337ea0a2b.js" crossorigin="anonymous" defer></script>
    <script src="{% static 'js/app.js' %}" defer></script>


</head>
<body>

<div class="modal fade back-drop" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<nav class="autohide navbar navbar-expand-lg sticky-top justify-content-between back-drop">

    <a class="nav-link active mx-4" href="{% url 'home:home' %}">
        <div class="row align-items-center m-2">
            <div class="col"><img src="{% static 'Images/favicon_lg.png' %}" style="height: 2rem"></div>
            <div class="col" style="margin-left: -1rem; margin-top: 1rem"><p class="fs-5"
                                                                             style="font-family: Judson,serif">
                Pet_Shop</p></div>
        </div>
    </a>
    <form action="{% url 'search:search_main' %}" method="get" class="d-none d-sm-block w-25 justify-content-center justify-content-center align-content-center mx-4">
        <div class="input-group">
            <input class="shadow-sm form-control main-btn-ps back-drop" type="search" name="search" placeholder="Search smth :)"
                   id="example-search-input">
            <button class="shadow-sm btn btn-primary search_btn" type="submit" style="align-content: start">
                <img src="{% static 'Images/Search.svg' %}" style="width: 75%">
            </button>
        </div>
    </form>

    {% if user.is_authenticated %}

        {% if user.theme.user_theme_theme == 1 %}
            <a href="{% url 'change_theme' %}" class=""><i class="fa-regular fa-moon"></i></a>
        {% else %}
            <a href="{% url 'change_theme' %}" class=""><i class="fa-solid fa-sun"></i></a>
        {% endif %}

    {% endif %}

    <div class="d-flex w-auto align-self-center mx-4" style="top: -1rem">
        <button class="navbar-toggler align-self-start align-content-start" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span>☰</span>
        </button>
        <div class="collapse navbar-collapse align-content-center m-2" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-content-end">
                
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/shop">Shop</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/blog">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/cart">Cart</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link active user__nav" aria-current="page" href="/accounts/profile">
                            {{ user.username | capfirst }}
                        </a>
                    {% else %}
                        <a class="nav-link active" aria-current="page" href="/login">Log in</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

<button onclick="topFunction()" class="btn upBtn" title="Go to top">
    <i class="fa-solid fa-arrow-up fa-2xs"></i>
</button>

<div class="wrapper_ps  overflow-hidden">
    <div class="content_ps overflow-hidden">

        <img src='{% static 'Images/Bg_tile_l.png' %}' style="position: absolute; z-index: -20" data-speed=".2">

        {% block content %}
            <h2>Some content</h2>
        {% endblock %}

        {% block right_side %}
        {% endblock %}

<div class="row footer ps-2 pe-2 min-vw-100 mt-5">
                <div class="col-12 col-md-3 ps-3 pe-3 footer__col">
                    © Aleksei Tishkov, 2024
                </div>
                <div class="col-12 col-md-6 ps-3 pe-3 footer__col">
                    Here will be site info
                </div>
                <div class="col-12 col-md-3 ps-3 pe-3 footer__col">
                    Here will be socials
                </div>
            </div>

    </div>

</div>
</body>
</html>

templates/base_bckp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Pet Shop
        {% endblock %}
    </title>

    {% load static %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href={% static 'css/bootstrap_skin.css' %} rel="stylesheet" media="screen">
    <link href={% static 'css/skin_default.css' %} rel="stylesheet" media="screen">

    <script src={% static 'js/bootstrap.min.js' %} defer></script>
    <script src={% static 'js/gsap.min.js' %} defer></script>
    <script src={% static 'js/ScrollTrigger.min.js' %} defer></script>
    <script src={% static 'js/ScrollSmoother.min.js' %} defer></script>
    <script src={% static 'js/app.js' %} defer></script>

</head>
<body>

<nav class="autohide navbar navbar-expand-lg sticky-top justify-content-between">

    <a class="nav-link active m-4" href="#">
        <div class="row align-items-center m-2">
            <div class="col"><img src="{% static 'Images/Logo.svg' %}"></div>
            <div class="col" style="margin-left: -1rem; margin-top: 1rem"><p class="fs-5"
                                                                             style="font-family: Judson,serif">
                Pet_Shop</p></div>
        </div>
    </a>
    <div class="d-none d-sm-block w-25 justify-content-center justify-content-center align-content-center m-4">
        <div class="input-group">
            <input class="shadow-sm form-control main-btn-ps back-drop" type="search" placeholder="Search smth :)"
                   id="example-search-input">
            <button class="shadow-sm btn btn-primary search_btn" type="button" style="align-content: start">
                <img src="{% static 'Images/Search.svg' %}" style="width: 75%">
            </button>
        </div>
    </div>

    <div class="d-flex w-auto align-self-center mx-4" style="top: -1rem">
        <button class="navbar-toggler align-self-start align-content-start" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span>☰</span>
        </button>
        <div class="collapse navbar-collapse align-content-center m-2" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-content-end">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Shop</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Cart</a>
                </li>
            </ul>
        </div>
    </div>

</nav>
<div class="wrapper_ps">
    <div class="content_ps">

        {% block content %}
            <h2>Some content</h2>
        {% endblock %}

    </div>
</div>
</body>
</html>

templates/page_400.html
{% extends 'base.html' %}

{% block title %}
    Error 404
{% endblock %}


{% block content %}
    <div class="main_container min-vh-100 hero-section">
            <p class="text-center mt-5" style="
                                    font-family: Koh Santepheap;
                                    font-size: 8rem;
                                    font-style: normal;
                                    font-weight: 700;
                                    line-height: 87%;
                        ">
                400
            </p>

            <p style="color: rgba(122, 122, 122, 0.80);
                                    font-family: Kodchasan;
                                    font-size: 2rem;
                                    font-style: normal;
                                    font-weight: 400;
                                    line-height: 107%;">
                Something went wrong<br>
with the request.
            </p>

    </div>

{% endblock %}

{% block content-right %}

<div class="h-100">

</div>

{% endblock %}

templates/page_403.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Error 403
{% endblock %}


{% block content %}
    <img src="{% static 'Images/Grumpy.webp' %}" alt="" class="grumpy-doggo">
    <div class="main_container min-vh-100 hero-section m-5 text-center">
            <h1 class="h1__error">
                403
            </h1>

            <h3 class="mt-5">
                It seems like you’ve tried to<br>
do something that you don’t<br>
have permission to.<br>
It’s ok, we just won’t let you! :)
            </h3>

    </div>

{% endblock %}

{% block content-right %}

<div class="h-100">

</div>

{% endblock %}

templates/page_404.html
{% extends 'base.html' %}

{% block title %}
    Error 404
{% endblock %}


{% block content %}
    <div class="main_container min-vh-100 hero-section">
            <p class="text-center mt-5" style="
                                    font-family: Koh Santepheap;
                                    font-size: 8rem;
                                    font-style: normal;
                                    font-weight: 700;
                                    line-height: 87%;
                        ">
                404
            </p>

            <h2 class="text-center" style="color: rgba(122, 122, 122, 0.80);
                       font-family: Kodchasan;
                       font-size: 2rem;
                       font-style: normal;
                       font-weight: 400;
                       line-height: 107%;">
                Unfortunately,<br>
                there  is no such page on our site.<br>
                But there are many other<br>
                good pages!<br>
            </h2>

    </div>

{% endblock %}

{% block content-right %}

<div class="h-100">

</div>

{% endblock %}

templates/page_500.html
{% extends 'base.html' %}

{% block title %}
    Error 404
{% endblock %}


{% block content %}
    <div class="main_container min-vh-100 hero-section">
            <p class="text-center mt-5 pt-5" style="
                                    font-family: Koh Santepheap;
                                    font-size: 8rem;
                                    font-style: normal;
                                    font-weight: 700;
                                    line-height: 87%;
                        ">
                500
            </p>

            <p class="text-center" style="color: rgba(122, 122, 122, 0.80);
                                    font-family: Kodchasan;
                                    font-size: 2rem;
                                    font-style: normal;
                                    font-weight: 400;
                                    line-height: 107%;">
                There’s a problem with the server.<br>
Try to access the page<br>
in a couple of minutes.
            </p>

    </div>

{% endblock %}

{% block content-right %}

<div class="h-100">

</div>

{% endblock %}

templates/pagination.html
    <div class="container">
        <div class="pagination justify-content-center">
            {% if page_obj.has_other_pages %}
                <div class="row">
                    {% if page_obj.has_previous %}
                        <a class="col btn page__num back-drop m-1" href="?page={{ page_obj.previous_page_number }}">
                            <
                        </a>
                    {% endif %}
                    {% for p in paginator.page_range %}
                        {% if page_obj.number == p %}
                        <a class="col btn page__num back-drop m-1 disabled">
                                {{ p }}
                        </a>
                        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                            <a class="col btn page__num back-drop m-1" href="?page={{ p }}">
                                {{ p }}
                            </a>

                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                            <a class="col btn page__num back-drop m-1" href="?page={{ page_obj.next_page_number }}">
                            >
                            </a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>

templates/two_cols.html
{% extends 'base.html' %}