Blog/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from Blog import views
from Blog.views import BlogViewSet

from Pet_Shop import settings

router = DefaultRouter()
router.register('posts', BlogViewSet, basename='spa_posts')

urlpatterns = [
    path('blog/', views.BlogView.as_view(), name='blog_main'),
    path('blog/add_post/', views.AddPost.as_view(), name='add_post'),
    path('blog/add_tag/', views.AddTag.as_view(), name='add_tag'),
    path('blog/delete_post/<slug:slug>/', views.DeletePostView.as_view(), name='delete_post'),
    path('blog/editorial/', views.AuthorPage.as_view(), name='editorial'),
    path('blog/editorial/<slug:slug>/', views.AuthorPostView.as_view(), name='view_post'),
    path('blog/edit_post/<slug:slug>/', views.EditPost.as_view(), name='edit_post'),
    path('blog/tag/<slug:tag_slug>/', views.TagView.as_view(), name='tag'),
    path('blog/author/<slug:author>', views.AuthorView.as_view(), name='post_authors'),
    path('blog/<slug:slug>/', views.PostView.as_view(), name='read_post'),
    path('spa/blog/', include(router.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pet_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page

from Pet_Shop.views import page_not_found, server_error, permission_error, request_error, change_theme_view
from django.contrib.sitemaps.views import sitemap
from Pet_Shop.sitemaps import sitemaps


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path('cookies', include("cookie_consent.urls")),
    path('', include('Home_Page.urls')),
    path('', include('Shop.urls')),
    path('', include('Blog.urls')),
    path('', include('User.urls', namespace='User')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('google_accounts/', include('allauth.urls'), name='google_auth'),
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('change_theme/', change_theme_view, name='change_theme'),
    path('search/', include('Search.urls')),

]

handler404 = page_not_found
handler500 = server_error
handler403 = permission_error
handler400 = request_error

admin.site.site_header = 'Pet_Shop Administration'
admin.site.index_header = 'Pet_Shop Administration'

Shop/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from Pet_Shop import settings
from Shop import views

urlpatterns = [
    path('shop/', views.ShopView.as_view(), name='shop_main'),
    path('shop/add_product/', views.ProductCreateView.as_view(), name='add_product'),
    path('shop/add_product_tag', views.AddProductTag.as_view(), name='add_product_tag'),
    path('shop/category/<slug:product_tag_slug>/', views.ProductTagView.as_view(), name='prod_category'),
    path('shop/editorial/', views.SellerPage.as_view(), name='shop_editorial'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('shop/edit_product/<slug:slug>/', views.EditProductView.as_view(), name='edit_product'),
    path('shop/product/<slug:slug>/', views.ProductView.as_view(), name='product_view'),
    path('shop/add_to_cart/<slug:slug>/', views.CartEntryCreator.as_view(), name='add_to_cart'),
    path('cart/clear_cart/', views.CartClearView.as_view(), name='clear_cart'),
    path('cart/delete/<int:pk>/', views.delete_cart_entry_view, name='cart_delete'),
    path('cart/edit_cart/<int:pk>', views.CartEditView.as_view(), name='edit_cart'),
    path('change-shipping-address/', views.change_address, name='change_address'),
    path('paypal/', include("paypal.standard.ipn.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/urls.py
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from django.urls import path
from User import views

app_name = 'User'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/login/', views.UserLogin.as_view(), name='login'),
    path('accounts/profile/', views.ProfilePage.as_view(), name='profile'),
    path('register/', views.register_user, name='register'),
    path('password-change/', views.UserPasswordChangeView.as_view(), name='change_password'),
    path('password-change/done/', views.password_changed, name='password_changed'),
    path('password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

Shop/views.py
import uuid

from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from django.views.generic.edit import FormView
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalFormView, BSModalUpdateView
from paypal.standard.forms import PayPalPaymentsForm

from Shop.forms import CreateProductForm, EditProductForm, ProductImagesForm, CartAdditionForm, CartEntryChange, \
    CartDeleteForm, AddressForm
from Shop.models import Product, Cart, ProductTag
from Pet_Shop.settings import PAYPAL_BUSINESS_EMAIL
from django.shortcuts import render

from Shop.services import link_product_photo_to_product, get_published_products, get_product_by_seller, \
    get_all_products, add_to_cart, get_product_by_slug, get_products_in_cart, get_cart_by_user, get_cart_sum, \
    clear_cart, delete_product_from_cart, get_available_products, add_address_to_cart, delete_address, get_product_tag, \
    get_products_by_tag


class ProductCreateView(LoginRequiredMixin, CreateView):
    form_class = CreateProductForm
    template_name = 'Shop/Product_create.html'
    extra_context = {'title': 'Add a new product'}

    def form_valid(self, form):
        form.instance.product_seller = self.request.user
        form.instance.product_slug = slugify(self.request.POST['product_name'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('edit_product', args=(self.object.slug,))


class EditProductView(UpdateView):
    model = Product
    form_class = EditProductForm
    success_url = reverse_lazy('shop_main')
    template_name = 'Shop/Product_create.html'
    image_form = ProductImagesForm()
    extra_context = {'title': 'Edit your product', 'image_form': image_form}

    def get(self, request, *args, **kwargs):
        __object = self.get_object()
        if __object.product_seller != request.user:
            raise PermissionDenied()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        __object = self.get_object()
        files = request.FILES.getlist('product_photo')
        for file in files:
            link_product_photo_to_product(__object, file)
        return super().post(request, *args, **kwargs)


class ShopView(ListView):
    template_name = 'Shop/Shop.html'
    model = Product
    paginate_by = 8
    extra_context = {'title': 'Shop'}

    def get_queryset(self):
        if self.request.user.is_authenticated:
            self.extra_context['cart'] = get_products_in_cart(self.request.user)
        return get_available_products()


class ProductView(DetailView):
    model = Product
    template_name = 'Shop/Product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}
        if self.object:
            context["object"] = self.object
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        if self.request.user.is_authenticated:
            context['cart'] = get_products_in_cart(self.request.user)
            context.update(kwargs)
        return super().get_context_data(**context)


class ProductTagView(ListView):
    template_name = 'Shop/Shop.html'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = get_product_tag(ProductTag, self)
        context['title'] = tag.product_tag_name.title()
        return context

    def get_queryset(self):
        return get_products_by_tag(self.kwargs['product_tag_slug'])


class SellerPage(ListView):
    template_name = 'Shop/Shop.html'
    paginate_by = 8
    extra_context = {
        'title': "Edit your products"
    }
    allow_empty = False

    def get_queryset(self):
        return get_product_by_seller(get_all_products(), self.request.user.pk)


class AddProductTag(CreateView):
    model = ProductTag
    fields = '__all__'
    template_name = 'Blog/Add_tag.html'
    success_url = reverse_lazy('shop_main')
    extra_context = {'title': 'Tag addition form'}


class CartEntryCreator(LoginRequiredMixin, BSModalCreateView):
    template_name = 'Shop/Cart_Addition.html'
    form_class = CartAdditionForm
    success_message = 'Product added to the cart'
    success_url = reverse_lazy('shop_main')
    extra_context = {'quantity': 1, 'name': None}

    def get_queryset(self):
        return get_product_by_slug(get_published_products(), self.kwargs['slug'])

    def form_valid(self, form):
        user = self.request.user
        form.instance.customer_id = user.pk
        _object = self.get_object()
        self.quantity = _object.product_quantity
        form.instance.customer_postalcode = user.user_postalcode
        form.instance.customer_address = user.user_address
        form.instance.product = _object
        if form.instance.quantity > self.quantity:
            form.instance.quantity = self.quantity
        if form.instance.quantity < 1:
            form.instance.quantity = 1
        return super().form_valid(form)


class CartEditView(LoginRequiredMixin, BSModalUpdateView):
    model = Cart
    template_name = 'Shop/Cart_Addition.html'
    form_class = CartEntryChange
    success_message = 'Cart was updated.'
    success_url = reverse_lazy('cart')


class CartView(LoginRequiredMixin, ListView):
    template_name = 'Shop/Cart.html'
    model = Cart

    def get_queryset(self):
        cart = get_cart_by_user(self.request.user)
        if not cart:
            return cart
        if cart[0].customer_postalcode and cart[0].customer_address:
            shipping_address = True
        else:
            shipping_address = False
        shipping_customer_postalcode = cart[0].customer_postalcode
        shipping_customer_address = cart[0].customer_address
        cart_sum = get_cart_sum(cart)
        if shipping_address:
            paypal_dict = {
                "business": PAYPAL_BUSINESS_EMAIL,
                "amount": cart_sum,
                "item_name": str(cart),
                "invoice": uuid.uuid4(),
                "notify_url": self.request.build_absolute_uri(reverse('paypal-ipn')),
                "return": self.request.build_absolute_uri(reverse('cart')),
                "cancel_return": self.request.build_absolute_uri(reverse('cart')),
            }
            form = PayPalPaymentsForm(initial=paypal_dict)
        else:
            form = AddressForm()
        self.extra_context = {'title': 'Cart', 'cart_sum': cart_sum, 'form': form,
                              'shipping_address': shipping_address,
                              'shipping_customer_postalcode': shipping_customer_postalcode,
                              'shipping_customer_address': shipping_customer_address}
        return cart

    def get(self, request, *args, **kwargs):
        self.get_queryset()
        return super(CartView, self).get(request, *args, **kwargs)

    def post(self, request):
        print(type(request.POST['customer_postalcode']))
        add_address_to_cart(request.user, request.POST['customer_postalcode'], request.POST['customer_address'])
        return redirect('cart')


class CartClearView(LoginRequiredMixin, BSModalFormView):
    model = Cart
    template_name = 'Shop/Cart_clear.html'
    success_url = reverse_lazy('shop_main')
    form_class = CartDeleteForm

    def post(self, request, *args, **kwargs):
        clear_cart(user=request.user.pk)
        return super().post(request, *args, **kwargs)


def delete_cart_entry_view(request, pk):
    delete_product_from_cart(cart_pk=pk, user=request.user)
    return redirect('cart')


def change_address(request):
    cart = get_cart_by_user(request.user)
    delete_address(cart)
    return redirect('cart')

Shop/templates/Shop/Cart.html
{% extends 'base.html' %}
{% load shop_tags %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    {% load static %}
<div class="main_container vh-100 mt-5">
{% if object_list %}
<div class="container text-end">
<div class="p-1 table-responsive table__card mt-5 container back-drop text-start">
<table class="table table-striped table__card">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Total</th>
    </tr>
  </thead>
  <tbody>
    {% for p in object_list %}
    <tr>
      <td>{{ p.product.product_name }}</td>
      <td><p>{{ p.quantity }}
          {% if p.quantity_changed %}
              <i style="color: #d60000;" class="fa-solid fa-arrow-trend-down"
                 title="Since the time you've added this item to your cart, its quantity in our stock decreased. We're sorry... But there will be more soon!"></i>
          {% endif %}
      <a class="edit_cart" data-form-url="{% url 'edit_cart' p.pk %}" title="Change quantity">
          <i class="fa-solid fa-pencil ms-1" aria-hidden="true"></i>
      </a></p>
      </td>
      <td>{{ p.product.product_price }}</td>
      <td>{{ p.quantity | multiply:p.product.product_price }}</td>
      <td><a href="delete/{{ p.pk }}" title="Remove from cart" class="delete__btn">
        <i class="fa-solid fa-square-minus"></i>
          </a>
    </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
    <h3 class="mt-5 text-end">Total: ${{ cart_sum }}</h3>
    {% if shipping_address %}
        <p>Your purchase will be shipped to {{ shipping_customer_postalcode }}, {{ shipping_customer_address }}.</p>
        <p>Need to ship to another address? <a href="{% url 'change_address' %}">Tell us where!</a></p>
    {% endif %}
    <a class="btn mt-2" id="clear-cart">Clear cart</a>
        {% if shipping_address %}
            <a class="btn btn-primary mt-2">{{ form.render }}</a>
        {% else %}
            <div class="text-center justify-content-center">
            <p class="mt-3">You must provide a shipping address to complete the purchase</p>
            <div class="row justify-content-center">
                <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for f in form %}
                        <div class="col-auto">
                        <p class="form__title">{{ f.label }} </p>
                        <p>{{ f }}</p>
                        <p>{{ f.errors }}</p>
                    </div>
                {% endfor %}
                    <button type="submit" class="btn btn-primary mt-4 col-2 h-auto">
                        Confirm address
                    </button>
                </form>
            </div>
            </div>
        {% endif %}
    <div class="container">

    </div>
</div>
{% else %}
    <h2 class="mt-5">Your cart is empty</h2>
{% endif %}
</div>

{% endblock %}

Shop/templates/Shop/Cart_Addition.html
<form method="post" action="">
  {% csrf_token %}

 <div class="modal-header">
    <h2 class="modal-title">Add product to cart</h2>
    <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close">
    </button>
  </div>

  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} invalid{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn" data-bs-dismiss="modal">Cancel</button>
    <button type="submit" class="btn btn-primary">Add to cart</button>
  </div>

Shop/templates/Shop/Cart_clear.html
<form method="post" action="">
  {% csrf_token %}

 <div class="modal-header">
    <h2 class="modal-title">Are you sure you want to clear your cart?</h2>
    <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close">
    </button>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn" data-bs-dismiss="modal">Cancel</button>
    <button type="submit" class="btn btn-primary">Clear cart</button>
  </div>

</form>

Shop/templates/Shop/Product_card.html
<div class="card m-2 text-center">
    <div class="card__wrapper vh-auto container back-drop">
        <div class="p-2  text-center">

            <img class="card__image mt-2"
                 src={{ p.product_main_photo.url }}
                         class="card-img-top" alt="..."
                 style="border-radius: 0.7rem">
        </div>
        <div class="card-body d-flex flex-wrap">
            <div class="container p-0">
                <h5 class="card-title">{{ p.product_name }}</h5>
                <p class="card-text d-none d-lg-block">{{ p.product_short_description }}</p>
            </div>
            <div class="container p-0">
                <div class="d-flex justify-content-end mb-2"
                     style="font-family: KohSantepheap,serif">${{ p.product_price }}
                </div>
                <div class="d-flex justify-content-end">
                    <a type="button"
                       class="btn m-1"
                       href="{% url 'product_view' p.slug %}"
                       style="width: 50%; max-height: 2.4rem"
                       title="More info">
                        <i class="fa-solid fa-circle-info"></i>
                    </a>
                    {% if user.is_authenticated %}
                        {% if p in cart %}
                            <button type="button"
                                    id="add_to_cart"
                                    class="btn m-1 add_to_cart bs-modal disabled"
                                    data-form-url="{% url 'add_to_cart' p.slug %}"
                                    style="width: 50%; max-height: 2.4rem"
                                    title="Already in a cart">
                            <i class="fa-solid fa-cart-arrow-down"></i>
                            </button>

                        {% else %}
                            <a type="button"
                                    id="add_to_cart"
                                    class="btn m-1 add_to_cart bs-modal"
                                    data-form-url="{% url 'add_to_cart' p.slug %}"
                                    style="width: 50%; max-height: 2.4rem"
                                    >
                                <i class="fa-solid fa-cart-plus" title="Add to cart"></i>
                            </a>
                        {% endif %}
                    {% else %}
                        <a type="button"
                                    id="add_to_cart"
                                    class="btn m-1 add_to_cart bs-modal"
                                    data-form-url="{% url 'add_to_cart' p.slug %}"
                                    style="width: 50%; max-height: 2.4rem"
                                    >
                                <i class="fa-solid fa-cart-plus" title="Add to cart"></i>
                            </a>
                    {% endif %}
                </div>
                <div class="d-flex justify-content-center">
                    {% if user.id == p.product_seller_id %}
                       <a class="btn btn-primary m-1" href="{% url 'edit_product' p.slug %}"
                           style="width: 100%; max-height: 2.4rem"
                           title="Edit the product">
                            <i class="fa-solid fa-pencil"></i>
                       </a></div>

                        <div><p>In stock: {{ p.product_quantity }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

Shop/templates/Shop/Product_card_child.html
<div class="card card-children text-center" style="--i:1;">
    <div class="card__wrapper container back-drop">
        <div class="p-2 text-center">
            <img class="card__image mt-2"
                 src={{ p.product_main_photo.url }}
                         class="card-img-top" alt="..."
                 style="border-radius: 0.7rem">
        </div>
        <div class="card-body d-flex align-content-between flex-wrap">
            <div class="container">
                <h5 class="card-title">{{ p.product_name }}</h5>
                <p class="card-text d-none d-lg-block">{{ p.product_short_description }}</p>
            </div>
            <div class="container">
                <div class="d-flex justify-content-end mb-2"
                     style="font-family: KohSantepheap,serif">${{ p.product_price }}
                </div>
                <div class="d-flex justify-content-end">
                    <a type="button"
                       class="btn m-1"
                       href="{% url 'product_view' p.slug %}"
                       style="width: 50%; max-height: 2.4rem">
                        <i class="fa-solid fa-circle-info"></i>
                    </a>
                    <a type="button"
                       class="btn m-1"
                       href="{% url 'product_view' p.slug %}"
                       style="width: 50%; max-height: 2.4rem">
                        <i class="fa-solid fa-circle-info"></i>
                    </a>
                </div>
                <div class="d-flex justify-content-center">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card card-children text-center" style="--i:2; top: 5px; left: 5px">
    <div class="card__wrapper container back-drop">
        <div class="p-2 text-center">
            <img class="card__image mt-2"
                 src={{ p.product_main_photo.url }}
                         class="card-img-top" alt="..."
                 style="border-radius: 0.7rem">
        </div>
        <div class="card-body d-flex align-content-between flex-wrap">
            <div class="container">
                <h5 class="card-title">{{ p.product_name }}</h5>
                <p class="card-text d-none d-lg-block">{{ p.product_short_description }}</p>
            </div>
            <div class="container">
                <div class="d-flex justify-content-end mb-2"
                     style="font-family: KohSantepheap,serif">${{ p.product_price }}
                </div>
                <div class="d-flex justify-content-end">
                    <a type="button"
                       class="btn m-1"
                       href="{% url 'product_view' p.slug %}"
                       style="width: 50%; max-height: 2.4rem">
                        <i class="fa-solid fa-circle-info"></i>
                    </a>
                    <a type="button"
                       class="btn m-1"
                       href="{% url 'product_view' p.slug %}"
                       style="width: 50%; max-height: 2.4rem">
                        <i class="fa-solid fa-circle-info"></i>
                    </a>
                </div>
                <div class="d-flex justify-content-center">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card mt-2  text-center" style="top: 10px; left: 10px">
    <div class="card__wrapper container back-drop">
        <div class="p-2 text-center">
            <img class="card__image mt-2"
                 src={{ p.product_main_photo.url }}
                         class="card-img-top" alt="..."
                 style="border-radius: 0.7rem">
        </div>
        <div class="card-body d-flex align-content-between flex-wrap">
            <div class="container">
                <h5 class="card-title">{{ p.product_name }}</h5>
                <p class="card-text d-none d-lg-block">{{ p.product_short_description }}</p>
            </div>
            <div class="container">
                <div class="d-flex justify-content-end mb-2"
                     style="font-family: KohSantepheap,serif">${{ p.product_price }}
                </div>
                <div class="d-flex justify-content-center">
                    <a type="button"
                       class="btn m-1"
                       href="{% url 'product_view' p.slug %}"
                       style="width: 50%; max-height: 2.4rem">
                        <i class="fa-solid fa-circle-info"></i>
                    </a>
                    {% if user.is_authenticated and p not in cart %}
                        <button type="button"
                                    id="add_to_cart"
                                    class="btn m-1 add_to_cart bs-modal"
                                    data-form-url="{% url 'add_to_cart' p.slug %}"
                                    style="width: 50%; max-height: 2.4rem"><i class="fa-solid fa-cart-plus"></i>
                        </button>
                    {% else %}
                        <button type="button"
                                    id="add_to_cart"
                                    class="btn m-1 add_to_cart bs-modal disabled"
                                    data-form-url="{% url 'add_to_cart' p.slug %}"
                                    style="width: 50%; max-height: 2.4rem"><i class="fa-solid fa-cart-arrow-down"></i>
                        </button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

Shop/templates/Shop/Product_categories.html
{% for category in product_categories %}
    <a href="{{ category.get_absolute_url }}"> <button class="btn tag">{{ category }}</button> </a>
{% endfor %}

Shop/templates/Shop/Product_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="main_container min-vh-100 hero-section">
        <div class="main_block mt-5">
            <div class="row h-50">
                <div class="col-md-4 text-center">

                    <div class="container align-items-center mt-5">
                        <div id="carouselExampleFade" class="carousel slide carousel-fade mt-2" data-bs-ride="carousel"
                        style="height: 80%">
                          <div class="carousel-inner">
                                <div class="carousel-item active text-center" data-bs-interval=3000">
                                  <img src="{{ product.product_main_photo.url }}"
                                       class="product__carousel__photo d-block w-100" alt="...">
                                </div>
                              {% for p in product.product_photo.all %}
                                <div class="carousel-item text-center" data-bs-interval="3000">
                                  <img src="{{ p.product_photo.url }}"
                                       class="product__carousel__photo d-block w-100" alt="...">
                                </div>
                              {% endfor %}
                          </div>
                          <button class="carousel-control-prev" type="button"
                                  data-bs-target="#carouselExampleFade"
                                  data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                          </button>
                          <button class="carousel-control-next" type="button"
                                  data-bs-target="#carouselExampleFade"
                                  data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                          </button>
                        </div>
                    </div>
                <div class="mt-5">
                {% if user.is_authenticated %}
                {% if product in cart %}
                <button type="button"
                        id="add_to_cart"
                        class="btn w-100 m-2 add_to_cart disabled"
                        style="width: 50%; max-height: 2.4rem">In cart
                </button>
                {% else %}
                <button data-form-url="{% url 'add_to_cart' product.slug %}" class="btn w-100 m-2 add_to_cart">
                    Add to cart
                </button>
                {% endif %}
            {% else %}
                <button data-form-url="{% url 'add_to_cart' product.slug %}" class="btn w-100 m-2 add_to_cart disabled">
                    Add to cart
                </button>
                <p>You have to be <a href="{% url 'User:login' %}">logged in</a> <br>to make an order</p>
            {% endif %}
            </div>
                </div>
            <div class="mt-5 col-md-6">
                <h1 class="blog_body p-0 text-center text-md-start">{{ product.product_name }}</h1>
                <h3 class="mt-2 text-center text-md-start"><p>{{ product.product_short_description }}</p></h3>
                <p class="text-center text-md-start">{{ product.product_description }}</p>

            </div>
            <div class="mt-5 col-md-2 text-center">

            <div class="mt-4">

                {% if product.related_post.exists %}
                    {{ product.related_post }}

                    <p>Read more about this product!</p>

                    {% for post in product.related_post.iterator %}
                        <div class="blog_post p-2 mb-2">
                        <p>{{ post.title.upper }}</p>
                        <img src="{{ post.main_photo.url }}" alt="" style="width: 90%">
                        <p>{{ post.summary }}</p>
                        <button href="{% url 'read_post' post.slug %}" class="btn m-2">Read post</button>

                        </div>
                    {% endfor %}

                {% endif %}

            </div>
            </div>
            </div>
        </div>
    </div>

{% endblock %}

Shop/templates/Shop/Shop.html
{% extends 'Shop/shop_base.html' %}

{% block shop_title %}
    {{ title }}
{% endblock %}

{% block shop_content %}
    {% load static %}
    <div class="row mt-3 w-auto" id="card-row">
            {% for p in object_list %}
                {% include 'Shop/Product_card.html' %}
            {% endfor %}
    </div>
{% endblock %}